_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "../models/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone_better"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0, 2.0, 3.0]]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 2
  RPN:
    SMOOTH_L1_BETA: 1.0
    IGNORE_IOA: False
    TOP_PROPOSALS_ALL_LEVEL: True
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    BOUNDARY_THRESH: -1
    UPDATE_MATCHES: True
    GET_GT_PER_LEVEL: True
  ALLOW_BOX_OUT_OF_BOUNDARY: True
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 1.0
  ROI_HEADS:
    NUM_CLASSES: 1
    IGNORE_IOA: True
    POSITIVE_FRACTION: 0.5
  FPN:
    NORM: "BN"
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1400
  MAX_SIZE_TEST: 1400
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
DATASETS:
  TRAIN: ("crowdhuman_train",)
  TEST: ("crowdhuman_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.04
  STEPS: (18750, 24375)
  MAX_ITER: 28125
  CHECKPOINT_PERIOD: 4000
  WARMUP_ITERS: 800
  WARMUP_FACTOR: 0.1
TEST:
  EVAL_PERIOD: 1000
  EVAL_START: 12000
  DETECTIONS_PER_IMAGE: 200
SEED: 11301414
OUTPUT_DIR: "../models/baseline"
# 44.6
