_BASE_: "./R-50-crowdhuman.yaml"
MODEL:
  OVERLAP_BOX_HEAD:
    ENABLE: True
    BUILD_ON_ROI_FEATURE: True
    OVERLAP_IOU_THRESHOLD: 0.4
    REG_LOSS_COEFF: 1.0
    UNIFORM_REG_DIVISOR: True
    PROB_LOSS_BETA: 0.02
OUTPUT_DIR: "../models/noh-NMS"
